### ISSUE TITLE
Adding dmarc record type

### ISSUE THREAD

**Issue by srknzl** [blechschmidt/massdns#109]
* We can add a new record type "DMARC", and to find DMARC records, massdns could ask TXT record of `_dmarc.example.com` to retrieve DMARC record. Then we can delete "_dmarc." part from the output. 

* Retrieving dmarc: https://serverfault.com/a/625020

**Comment by mzpqnxow** [comment]
@srknzl I don't disagree that the DMARC data is very useful but I don't like the idea of the output being "lossy" or otherwise modified from it's original form. I think it's best as it is now, reporting *all* `TXT` responses without modifying them and allowing easy postprocessing on the NDJSON file

To elaborate on the way I think about it, massdns is very good at:

1. Fast, asynchronous tx/rx
2. Encoding/decoding of DNS questions/answers
3. Status output and logging of raw results

It is not intended to modify or postprocess the data, aside from the minimum amount needed to serialize it into a lossless NDJSON format. I think this sort of functionality is best implemented separately from massdns

I recommend you check out [the scripts directory](https://github.com/blechschmidt/massdns/tree/master/scripts)  to see some of the post-processing scripts that have been contributed and included. I think a script or application that does what you describe to a "raw" NDJSON output file would be a better way to approach this

Just my opinion, of course!

**Comment by srknzl** [comment]
Yeah, actually we do postprocessing in our software which uses massdns. I think you'r right, I am not sure if I will add that script. However, I hope this issue will be beneficial any way, for those search for "dmarc" in issues.

So closing this as I agree your point
