### ISSUE TITLE
Multiple source ports

### ISSUE THREAD

**Issue by chanduusc** [blechschmidt/massdns#15]
Is it possible to have multiple ports rather than re-using same port...if one dns request is detected by threat as a firewall, all consequent queries match same session and gets discarded

**Comment by blechschmidt** [comment]
Due to massdns using a single socket, it is not currently possible to randomize the source ports without the use of additional tools.
Using the `packetrand` tool from the [freebind project](https://github.com/blechschmidt/freebind#source-port-randomization), which now supports source port randomization, you should be able to achieve what you want though. You would bind MassDNS to a fixed port in this case and instruct `iptables` to pass all packets to and from the DNS resolvers to the netfilter queue which `packetrand` is attached to and specify the MassDNS port using `packetrand`'s `-r` argument.
