### ISSUE TITLE
It takes lot of time and -c 200 count does not cover 100000 entry ....

### ISSUE THREAD

**Issue by yam23** [blechschmidt/massdns#20]
It could be very dump question or some mistake with my configuration of vmware instant ....
I apologies in advance for that ....

It takes lot of time on my machine ....I used it on Kali-Linux-Light-2017.1-vm-amd64 , when I tried domain list of100000 it does not complete with 200 count also ... i used below command ....
./subbrute.py names.txt example.com | ./bin/massdns -r resolvers.txt -t A -a -o -w results.txt - 
It does not complete even 15000 checks ..... and it takes less than a minute
with below command for 50000 checks , 
./subbrute.py names.txt example.com | ./bin/massdns -r resolvers.txt -t A -a -o -c 100 -w results.txt -
It covers 24000 entry in 4-5 mintues ..... 
my ultimate aim is to use all.txt prepared by Jason(awesome presentation on LevelUp) , I came to know from there about massdns.....

I have allocated 8 cores and 3 gb RAM....It never crosses even 6 digit check.....I even tried with -c 200 count but it takes 14-15 minutes and completes with 75K entry....

Am i missing some configuration of enabling parallel threading ? 

Thanks,

**Comment by blechschmidt** [comment]
MassDNS requires a decent amount of upload bandwidth in order for the default configuration to work. It is single-threaded because it is designed for scenarios in which the network is the bottleneck.

In order to obtain more reliable results, try adjusting the size of the internal hash map using the `-s` parameter which controls the amount of concurrent lookups. Depending on your upload bandwidth, `1000` might be a reasonable value if you are using MassDNS with a conventional home internet connection. However, MassDNS is mainly designed to be run on servers with a high bandwidth like the 10$/month DigitalOcean VPS instance.

Nonetheless, the VM could be a bottleneck, too.

I will try to improve the README soon because it lacks an explanation of how MassDNS works internally and I think the correlation between the `-s` parameter and performance is not quite obvious.

**Comment by yam23** [comment]
You are awesome !! I was suspecting same as my network was getting slow
when I was running the same, I need to find out some VPS instance
or divide large domain files and run massdns on chuncks during night with
masscan after that ....

I will explore -s parameter as you suggested , hopefully this weekend ....

Thanks for Detail Explanation !!

Cheers,
Anis
