### ISSUE TITLE
The parameter "--type" or "-t" does not seem to work. 

### ISSUE THREAD

**Issue by shmilylty** [blechschmidt/massdns#63]
The parameter "--type" or "-t" does not seem to work.. From the result, other DNS record types are queried.

My run command:.\bin\massdns.exe -r .\lists\resolvers.txt --type A -o J  -w .\bin\qq.json .\bin\qq.txt
![image](https://user-images.githubusercontent.com/24275308/77250515-6ccb4d80-6c83-11ea-9fc1-d80afec3e524.png)

Is there a way for massdns to query only the specified DNS record type?

Massdns is an excellent tool, looking forward to your reply ~

**Comment by blechschmidt** [comment]
When an `A` record is queried, it is perfectly fine for a resolver to return a `CNAME` record. This is expected behavior. In your case, `massdns` queries `A` records but there is just a `CNAME` alias. `CNAME` flattening (i.e. pretending the `A` record of the `CNAME` alias was the `A` record of the domain you queried) is not supported.
