### ISSUE TITLE
Problem with multiple filter option.

### ISSUE THREAD

**Issue by 0xd0m7** [blechschmidt/massdns#78]
Hi !
i am seeing that filter option does not return any result for some states, by other hand it's not possible to choose multiple filters.
For example, how can filter NXDOMAIN,SERVFAIL and REFUSED only ignoring OK or NOERROR status and dump them into a file?. What i am missing?

Thanks in advance.

**Comment by blechschmidt** [comment]
You can either use the `--filter` option multiple times, i. e. `--filter NXDOMAIN --filter SERVFAIL --filter REFUSED` to only output packets with these response codes or you can use `--ignore NOERROR` in order to output all packets except those with a `NOERROR` code (`NOERROR` is the canonical name of the status code for packets considered to be OK). I don't see any case in which you would want to use `--filter` and `--ignore` at the same time.

**Comment by 0xd0m7** [comment]
@blechschmidt thanks for your quick response!
But it seems that i missing something. For example when i add --filter NOERROR option massdns generated a 0byte output file. And it seems that does not me show me domains with SERVFAIL, NXDOMAIN, or REFUSED state in this file. This is that i am waiting when i add this option.
How can I extract these domains in a list?

Thanks in advance
